- package:
  - name: dynamizer
  - section:
    - name: exe:dynamizer
    - message:
      - name: Redundant build-depends entry
      - depends:
        - dynamizer-lib
  - section:
    - name: test:test
    - message:
      - name: Redundant build-depends entry
      - depends: dynamizer-lib

